///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AlbumPhotos {
/*
{
  "albumId": 1,
  "id": 1,
  "title": "accusamus beatae ad facilis cum similique qui sunt",
  "url": "https://via.placeholder.com/600/92c952",
  "thumbnailUrl": "https://via.placeholder.com/150/92c952"
} 
*/

  int? albumId;
  int? id;
  String? title;
  String? url;
  String? thumbnailUrl;

  AlbumPhotos({
    this.albumId,
    this.id,
    this.title,
    this.url,
    this.thumbnailUrl,
  });
  AlbumPhotos.fromJson(Map<String, dynamic> json) {
    albumId = json['albumId']?.toInt();
    id = json['id']?.toInt();
    title = json['title']?.toString();
    url = json['url']?.toString();
    thumbnailUrl = json['thumbnailUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['albumId'] = albumId;
    data['id'] = id;
    data['title'] = title;
    data['url'] = url;
    data['thumbnailUrl'] = thumbnailUrl;
    return data;
  }
}
